### ISSUE TITLE
No longer working. Does not build

### ISSUE THREAD

**Issue by andrewcheny** [sararob/angular2base#12]
Got the error when run npm run build:

ERROR in ./src/app.ts
Module build failed: TypeError: compiler.parseConfigFile is not a function
    at ensureTypeScriptInstance (/home/andrew/angularprj/angular2base/node_modules/ts-loader/index.js:147:38)
    at Object.loader (/home/andrew/angularprj/angular2base/node_modules/ts-loader/index.js:365:14)

Any ideas?

**Comment by goondu** [comment]
force the typescript version in package.json to version 1.6.2, and run npm install again.
"typescript": "1.6.2",

You should be able to build thereafter.
